### ISSUE TITLE
Process globs on <files> argument

### ISSUE THREAD

**Issue by silverwind** [silverwind/ver#6]
Apparently it is possible that unexpanded globs can pass through to the application on Windows, should support this.

**Comment by silverwind** [comment]
@the-j0k3r: would you mind posting the output of `node -p process.argv *`?

**Comment by the-j0k3r** [comment]
```js
> node -p process.argv *
[ ?[32m'C:\\Program Files\\nodejs\\node.exe'?[39m, ?[32m'*'?[39m ]
```
