### ISSUE TITLE
Request: prompt user to to add commit message on tag

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/ver#8]
Would it be possible to add a prompt asking user to add a message on tagging `npm run major|minor|patch`?

This would come in handy so as to show a list of changes in the release/tag views on a given tag.

Atm the only way to do this is manually unless Im missing something.

Thanks

**Comment by the-j0k3r** [comment]
@siverwind ping.

**Comment by silverwind** [comment]
Are you referring to the GitHub release feature? I'm not sure if it's possible to write that message in the CLI. `git tag` allows multiple `-m` (the first is always the version), for example:

```
git tag -a 0.0.3 -m 0.0.3 -m "message1" -m "message2" -m "message3"
```

results in:

https://github.com/silverwind/symlink-test/releases/tag/0.0.3
https://github.com/silverwind/symlink-test/releases

So I could see a option to launch `$EDITOR` and let the user write some paragraphs, then parsed and splittet to multiple `-m` options for git.

**Comment by the-j0k3r** [comment]
Well what you describe it would be https://github.com/StylishThemes/GitHub-Dark/issues/1011

The first message `-m 0.0.3` is what I request here like adding some prefix like `-m Prepare release 0.0.3`

**Comment by silverwind** [comment]
New `-m` argument available. Example:

```
ver patch -m 'Release _VER_' -m 'This is a great release'
```

To replicate what the default behaviour was before:

```
ver patch -m '_VER_'
