### ISSUE TITLE
Request: prompt for a prefix on version commit message

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/ver#9]
At the moemnt the result commit reads only e.g. 1.0.0` but it would be nice if we could enter a prefix either on a config file or prompted to enter a prefix.

Useful prefixes would be:

* Release x.y.z
* custom

Thanks

**Comment by the-j0k3r** [comment]
@siverwind ping.

**Comment by silverwind** [comment]
The first tag message is hardcoded at `-m ${newVersion}`, but I could see adding a option to manually specify it. We would need a token to replace the version in the string.

**Comment by silverwind** [comment]
See https://github.com/silverwind/ver/issues/8#issuecomment-541433946
